language: c

os:
  - linux

before_install:
  - sudo apt-get update -y
  - sudo apt-get install libncurses5-dev
  - sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386
  - sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so
  - sudo apt-get install -y ccache &&echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc &&source ~/.bashrc && echo $PATH
  - export USE_CCACHE=1

before_script:
# Download the toolchain
  - git clone "https://bitbucket.org/UBERTC/aarch64-linux-android-4.9" "$HOME/UBERTC"

# Download the Kernel Sources
  - git clone --depth=50 --branch=Alpha https://github.com/psycho-source/Psycho-Kernel $HOME/kernel

script:
  - export ARCH=arm64
  - export SUBARCH=arm64
  - export CROSS_COMPILE="$HOME/UBERTC/bin/aarch64-linux-android-"
  - cd $HOME/kernel
  - make clean && make mrproper
  - make x500_defconfig
  - make -j8

